### ISSUE TITLE
Livekit plugin for Waves API

### ISSUE THREAD

**Issue by smallest-admin** [smallest-inc/waves-examples#2]
@hamees-sayed can you add a short description here?

**Comment by hamees-sayed** [comment]
https://github.com/livekit/agents/pull/890

PR for smallest integration

**Comment by hamees-sayed** [comment]
raised a pr to waves-example with livekit example
https://github.com/smallest-inc/waves-examples/pull/4

**Comment by sapien-akshat** [comment]
@hamees-sayed ping the author to merge the livekit pr
