### ISSUE TITLE
Create PR for Lightning integration to Vocode

### ISSUE THREAD

**Issue by smallest-admin** [smallest-inc/waves-examples#3]

**Comment by smallest-admin** [comment]
@Divyansh-opp issues should not be moved to closed without a description or a PR link

**Comment by Divyansh-opp** [comment]
Added Smallest.ai synthesizer to vocode and also made it a default synthesizer. Integration of Lightning model is done. 
Here is the PR link: 
https://github.com/vocodedev/vocode-core/pull/721
