### ISSUE TITLE
Waves example repo revamp

### ISSUE THREAD

**Issue by smallest-admin** [smallest-inc/waves-examples#6]
1. Waves and Smallest AI logos, social media URLs - ask devansh
2. Twillio, Plivo, Vonage examples
3. Livekit examples - PR raised
4. Best practice examples for generating audio
5. Best practices for network latency
6. URLs to any PR/code lying in any other repository where waves API is used
7. Link to waves python SDK - Available through pip - create separate ticket for this
8. Link to waves nodejs SDK - Available through npm - create separate ticket for this

Languages should be python and node js.

**Comment by sapien-akshat** [comment]
@wasimmadha  send the branch for plivo streaming to @hamees-sayed

**Comment by hamees-sayed** [comment]
vonage and plivo example added by wasim - feature/telephone_example ✅
new readme ✅
livekit example pr raised - [pull/4](https://github.com/smallest-inc/waves-examples/pull/4)

**Comment by sapien-akshat** [comment]
@krakenftw @sapien-akshat add voices, lanugages to db so that we can add that to sdk. 
@wasimmadha feature to think about - audio timestamp

**Comment by hamees-sayed** [comment]
bolna example

**Comment by sapien-akshat** [comment]
add links to sdk @hamees-sayed

**Comment by hamees-sayed** [comment]
sdk: https://github.com/smallest-inc/smallest-python

**Comment by hamees-sayed** [comment]
document usage for every method in sdk

**Comment by hamees-sayed** [comment]
add deprecation message for thunder
